# Generated by Django 4.1.1 on 2022-10-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
